from typing import Final, Self
from dataclasses import dataclass
from enum import Enum, auto

from pmark.parser.block.frame_spec import BlockParserFrameSpec
from pmark.parser.block.rule_context import BlockParserRuleContext
from pmark.parser.block.upcall import BlockParserUpcall, BlockParserUpcallKind


class BlockParserCommandKind(Enum):
    """
    Discriminant for parser commands that control the explicit stack machine's
    flow and state transitions.
    """

    INITIALIZE_ROOT_FRAME = auto()
    """
    Bootstrap the parser by creating the root frame.

    This command is used *exactly once* per parser invocation. It is not
    generated by any rule; instead, it is explicitly set as the `causal_command`
    of the root frame during parser initialization. All subsequent frames are
    created by other commands (e.g., `PARSE_NESTED`).
    """

    COMMIT_SUCCESS = auto()
    """
    The rule has successfully matched the input and reached a final accepting
    state.
    """

    COMMIT_REJECTION = auto()
    """
    The rule has definitively failed to match the input and reached a final
    rejecting state.
    """

    PARSE_NESTED = auto()
    """
    Parse a nested parsing region (e.g., the content of a list item or blockquote).

    Return this command when a rule needs to recursively process a subordinate part
    of the source with its own rule chain. The parser will suspend the current rule,
    parse the specified region independently, and then resume the original rule,
    making the nested result available for further processing.

    This enables clean handling of arbitrarily nested structures without explicit
    recursion in rule code. When this kind is used, the `frame_spec`
    field must contain a `BlockParserFrameSpec` that defines the nested context.
    """

    LOOKAHEAD_ANY_RULE_MATCHES = auto()
    """
    Test whether any rule in the given set matches the upcoming input without
    consuming characters.

    The parser evaluates the provided rule chain in *speculative mode*.
    If any rule reaches an accepting state, the lookahead returns
    `True`; otherwise it returns `False`.

    When this kind is used, the `frame_spec` field must contain a
    `BlockParserFrameSpec` whose `rule_chain` defines the set of rules to test
    speculatively.
    """


APPLICABLE_COMMAND_KINDS: Final[frozenset[BlockParserCommandKind]] = frozenset(
    {
        BlockParserCommandKind.COMMIT_SUCCESS,
        BlockParserCommandKind.LOOKAHEAD_ANY_RULE_MATCHES,
        BlockParserCommandKind.PARSE_NESTED,
    }
)
"""
Set of command kinds that terminate or suspend rule processing.
These represent successful completion or forced termination of the current rule chain.
"""

NESTING_COMMAND_KINDS: Final[frozenset[BlockParserCommandKind]] = frozenset(
    {
        BlockParserCommandKind.LOOKAHEAD_ANY_RULE_MATCHES,
        BlockParserCommandKind.PARSE_NESTED,
    }
)
"""
Set of command kinds that cause a new frame to be pushed onto the stack,
creating a nested parsing context.
"""

SPECULATIVE_SAFE_COMMAND_KINDS: Final[frozenset[BlockParserCommandKind]] = frozenset(
    {
        BlockParserCommandKind.COMMIT_SUCCESS,
        BlockParserCommandKind.COMMIT_REJECTION,
        BlockParserCommandKind.LOOKAHEAD_ANY_RULE_MATCHES,
    }
)
"""
Set of command kinds that are permitted when the parser is running in speculative mode.
Speculative mode must not consume characters;
only pattern matching and lookahead commands are allowed.
"""


@dataclass(slots=True, frozen=True)
class BlockParserCommand:
    """
    Instruction returned by a parser rule to control the parser's next action.

    A `BlockParserCommand` encapsulates a directive that tells the block parser
    how to proceed after a rule has finished its work. It is the primary
    communication channel from parser rules to the parser engine.

    Commands play a central role in the *upcall pattern*: when a rule creates
    a child frame (e.g., via `PARSE_NESTED`), the command stores the rule's
    context in `origin_rule_context`. When the child frame completes, it calls
    `return_results()`, which in turn invokes `deliver_results()` on this command.
    The command then forwards the result back to the originating rule's context,
    allowing the rule to resume with the child's output.

    Design Note:
        The architecture anticipates the possibility of evolving into a
        *discriminated union* (sum type) if future command variants require
        significantly different payloads. The current structure keeps the design
        simple until the need for more varied payloads arises.
    """

    kind: BlockParserCommandKind
    """
    The specific action the parser should perform. See `BlockParserCommandKind` for details.
    """

    child_frame_spec: BlockParserFrameSpec | None
    """
    Specification for creating a child frame, used by command kinds that initiate
    nested parsing contexts (`PARSE_NESTED` and `LOOKAHEAD_ANY_RULE_MATCHES`).
    For command kinds that do not create a child frame, this field must be `None`.
    """

    origin_rule_context: BlockParserRuleContext | None
    """
    The context of the rule that produced this command.

    When a rule returns a command to the parser engine, its current execution
    context must be captured and stored here. This allows the engine to later
    resume the rule (e.g., after a nested frame completes) or use the context
    when processing the command. For commands that do not originate from a rule
    with a context (e.g., synthetic commands injected by the parser itself),
    this field must be `None`.
    """

    @classmethod
    def with_commit_success_kind(cls) -> Self:
        """
        Return a command whose kind is `COMMIT_SUCCESS`.
        """
        return cls(
            kind=BlockParserCommandKind.COMMIT_SUCCESS,
            child_frame_spec=None,
            origin_rule_context=None,
        )

    @classmethod
    def with_commit_rejection_kind(cls) -> Self:
        """
        Return a command whose kind is `COMMIT_REJECTION`.
        """
        return cls(
            kind=BlockParserCommandKind.COMMIT_REJECTION,
            child_frame_spec=None,
            origin_rule_context=None,
        )

    def expect_child_frame_spec(self) -> BlockParserFrameSpec:
        """
        Return the child frame specification, asserting that it exists for this command kind.

        This method is intended to be called only after confirming that the command
        kind requires a child frame spec (i.e., `self.kind` is `PARSE_NESTED` or
        `LOOKAHEAD_ANY_RULE_MATCHES`). It provides a type-safe way to obtain the `not None`
        `child_frame_spec` without further optional checks, performing a runtime
        validation to uphold the invariant. If `child_frame_spec` is unexpectedly
        `None` - indicating an internal logic error or inconsistent state - a
        `ValueError` is raised.

        Returns:
            BlockParserFrameSpec: The child frame specification associated with the command,
            guaranteed to be `not None`.

        Raises:
            ValueError: If `self.child_frame_spec` is `None`, meaning the command kind does
                not require a child frame spec or the dataclass invariant has been violated.
        Example:
        ```python
            if cmd.kind in (BlockParserCommandKind.PARSE_NESTED,
                            BlockParserCommandKind.LOOKAHEAD_ANY_RULE_MATCHES):
                spec = cmd.expect_child_frame_spec()
        ```
        """

        if self.child_frame_spec is None:
            raise ValueError(
                f"Cannot get child frame spec: child_frame_spec is None for command kind {self.kind}, "
                "but a child frame specification is expected for this kind."
            )
        return self.child_frame_spec

    def expect_origin_rule_context(self) -> BlockParserRuleContext:
        """
        Return the origin rule context, asserting that it exists for this command.

        This method is intended to be called only after confirming that the command
        originated from a rule that had a captured context (i.e., `origin_rule_context`
        is not `None`). It provides a type-safe way to obtain the `not None` origin
        context without further optional checks, performing a runtime validation to
        uphold the invariant. If `origin_rule_context` is unexpectedly `None` -
        indicating an internal logic error or inconsistent state - a `ValueError` is raised.

        Returns:
            BlockParserRuleContext: The context of the rule that produced this command,
            guaranteed to be `not None`.

        Raises:
            ValueError: If `self.origin_rule_context` is `None`, meaning the command
                does not carry an origin rule context or the invariant has been violated.

        Example:
        ```python
            if cmd.origin_rule_context is not None:
                ctx = cmd.expect_origin_rule_context()
                parent_frame.capture_current_rule_context(ctx)
        ```
        """
        if self.origin_rule_context is None:
            raise ValueError(
                f"Cannot get origin rule context: origin_rule_context is None for command kind {self.kind}, "
                "but an origin rule context is expected for this command."
            )
        return self.origin_rule_context

    def deliver_upcall(self, upcall: BlockParserUpcall) -> None:
        """
        Deliver an upcall result to the context that originated this command.

        In the upcall pattern, this method is invoked (typically by a completing
        child frame) to pass the result of a nested operation back to the waiting
        context (e.g., a suspended rule).

        Args:
            upcall: The upcall object representing the result of the nested
                operation. Its structure is defined by `BlockParserUpcall`.
        """

        match upcall.kind:
            case BlockParserUpcallKind.LOOKAHEAD_ANY_RULE_MATCHED:
                if self.kind is not BlockParserCommandKind.LOOKAHEAD_ANY_RULE_MATCHES:
                    raise ValueError(
                        f"Cannot deliver LOOKAHEAD_ANY_RULE_MATCHED to command of kind {self.kind}. "
                        f"Expected LOOKAHEAD_ANY_RULE_MATCHES command."
                    )
                self.expect_origin_rule_context().lookahead_matched = upcall.payload

            case BlockParserUpcallKind.PARSE_NESTED_RESULT:
                if self.kind is not BlockParserCommandKind.PARSE_NESTED:
                    raise ValueError(
                        f"Cannot deliver PARSE_NESTED_RESULT to command of kind {self.kind}. "
                        f"Expected PARSE_NESTED command."
                    )
                self.expect_origin_rule_context().has_interblock_blank_line = (
                    upcall.payload
                )
